name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  b2-posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-24.04

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Boost
        run: |
          ./bootstrap.sh --with-libraries=signals,regex,thread,date_time --with-toolset=gcc
          ./b2 -j3 stage
